inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'puppet-languageserver'
  Exclude:
    - 'tmp/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - Gemfile
    - Rakefile

Style/Documentation:
  Enabled: false
Style/NumericLiterals:
  Enabled: false

# Length is not useful indicator
Layout/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false

# Empty method definitions over more than one line is ok
Style/EmptyMethod:
  Enabled: false

# Either sytnax for regex is ok
Style/RegexpLiteral:
  Enabled: false

# Sometimes, I actually want both!
Style/DateTime:
  Enabled: false

# Please don't fail at failing.
Lint/RedundantCopDisableDirective:
  Enabled: false

# Don't care
Naming/MemoizedInstanceVariableName:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false

# In some cases readability is better without these cops enabled
Style/ConditionalAssignment:
  Enabled: false
Style/Next:
  Enabled: false

# Line endings are just a mess
Layout/EndOfLine:
  Enabled: false

# We only alias for monkey patching
Style/Alias:
  Enabled: false

# Harder to read when on
Style/SymbolProc:
  Enabled: false
Style/HashSyntax:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Naming/RescuedExceptionsVariableName:
  PreferredName: e

# There's no benefit to this and can make things harder to read.
Style/NumericPredicate:
  Enabled: false

# This is not valid on Ruby 2.1
Style/SafeNavigation:
  Enabled: false

# This is not valid on Ruby 2.1
Layout/HeredocIndentation:
  Enabled: false

# Rubocop 0.80.0 rules
Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

# Rubocop 0.80.1 rules
Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: false
