#!/usr/bin/env ruby
# frozen_string_literal: true

# Add the language server into the load path
$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), 'lib'))
# Add the vendored gems into the load path
$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), 'vendor', 'hiera-eyaml', 'lib'))

require 'puppet_languageserver_sidecar'

PuppetLanguageServerSidecar.init_puppet_sidecar(PuppetLanguageServerSidecar::CommandLineParser.parse(ARGV))
PuppetLanguageServerSidecar.execute_and_output(PuppetLanguageServerSidecar::CommandLineParser.parse(ARGV))
